import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { PrimeReactProvider } from "primereact/api";
import RecoilContextProvider from "~/lib/RecoilContextProvider";

export const metadata: Metadata = {
  title: "CainanDrive",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <RecoilContextProvider>
      <ClerkProvider>
        <PrimeReactProvider>
          <html lang="en" className={`${GeistSans.variable}`}>
            <body>{children}</body>
          </html>
        </PrimeReactProvider>
      </ClerkProvider>
    </RecoilContextProvider>
  );
}
